### ISSUE TITLE
Query regarding the Training details

### ISSUE THREAD

**Issue by arshagarwal** [jiechen2358/FaceAging-by-cycleGAN#5]
1. What was the number of training and testing samples used?
2.What was the batch size used?
3.How long did it take to complete an epoch?
Thanks.

**Comment by jiechen2358** [comment]
> 1. What was the number of training and testing samples used?
>    2.What was the batch size used?
>    3.How long did it take to complete an epoch?
>    Thanks.

We did training and testing on AWS. You can have a try. The more powerful server you choose, the faster.

**Comment by arshagarwal** [comment]
Oh okay,Thanks for answering.
